version: '3'
services:
  wordpress:
    image: andreccosta/wordpress-xdebug
    volumes:
      - .:/workspace
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('DOMAIN_CURRENT_SITE', 'localhost');
        define('PATH_CURRENT_SITE', '/');
        define( 'WP_DEBUG_LOG', true );
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - 9000:9000
